server:
  port: 9100 # ????port?

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ToDoLsit # h2 database ????
    driver-class-name: org.h2.Driver # ??driver
    username: sa # database ???
    password:  # database ??

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5

