server:
  port: 9100 # ????port?

spring:
  messages:
    fallback-to-system-locale: false # 找不到當前語言檔時，至系統默認index.properties
    basename: static/lang/index # 將語言檔配置在static/lang底下，預設為index
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ToDoLsit # h2 database ????
    driver-class-name: org.h2.Driver # ??driver
    username: sa # database ???
    password:  # database ??

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5

